/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ts_kernel_h
#define _ts_kernel_h


void
step_forward_2d(float** restrict u0, float** restrict u1, float** restrict vel,
                float** restrict rho, float* restrict fdcoef_d2,
                float* restrict fdcoef_d1, int nop, int nzpad, int nxpad);
/*< 2D FD time-stepping with SIMD vectorization support >*/


void
step_forward_3d(float*** restrict u0, float*** restrict u1,
                float*** restrict vel, float*** restrict rho,
                float* restrict fdcoef_d2, float* restrict fdcoef_d1, int nop,
                int nzpad, int nxpad, int nypad);
/*< 3D FD time-stepping with SIMD vectorization support >*/

#endif
