from rsf.proj import *
import sys, os

sys.path.append('/home/byrne/WORK/CODE')
import byrne_awe as awe

import math, fdmod, encode, wemig, stiffness

pi = 3.14159
# define paxmterers
par = {
    # model dimensions
    'nx':600,'ox':0,'dx':0.00025,'lx':'x','ux':'km',
    'nz':400,'oz':0,'dz':0.00025,'lz':'z','uz':'km',
    # time paxmeters
    'kt':100, 'frq':600,
    'nt':1600, 'ot':0, 'dt':0.000025, 'lt':'t', 'ut':'s',
    # model paxms
    'snap':'y','bnds':'y','jsnap':20,'height':6,
    'nb':32,'nbell':5,'jdata':1,'dabc':'y',
    'free':'y','ssou':'y','nc':1,'gpu':0,
    # output params
    'xz':'y'
}

# initialize paxms in ze fdm model
fdmod.param(par)
par['nframe'] = 20
par['iframe'] = 8

# zomsen paxms
par['vp'] = 2

# genexte velocity file
Flow('vp',None,'''spike nsp=1 mag=%(vp)g n1=%(nz)d o1=%(oz)g d1=%(dz)g n2=%(nx)d o2=%(ox)g d2=%(dx)g |
        put label1=%(lz)s label2=%(lx)s unit1=%(uz)s unit2=%(ux)s''' % par)

# make wavelet
awe.wavelet('wav',par['frq'], '', par)

# gen receiver arxy
receiver_par = par
receiver_par['ox'] = par['oz']
receiver_par['nx'] = par['nz']
receiver_par['dx'] = par['dz']
receiver_par['lx'] = par['lz']
receiver_par['ux'] = par['uz']
receiver_par['oz'] = par['ox']
receiver_par['nz'] = par['nx']
receiver_par['dz'] = par['dx']
receiver_par['lz'] = par['lx']
receiver_par['uz'] = par['ux']

rec_z = par['ox'] + par['nx'] * par['dx']

fdmod.horizontal('rr-2d', rec_z, par)

#fdmod.horizontal('ss-2d', 0.04, par)
xsou = par['ox']+(par['nx']-1)*par['dx']/2.
zsou = par['oz']+(par['nz']-1)*par['dz']/4.

# gen point source
fdmod.point('ss-2d', xsou, zsou, par)

par = awe.param(par)

awe.awefd2d('dat', 'wfl', 'wav',  'vp', None, 'ss-2d', 'rr-2d', '', par)

Result('dat', 'window | transp | grey')

Result('wfl', 'window | grey gainpanel=a')

End()
